"""add hockey and oscar tables

Revision ID: ef7cf35ece55
Revises: 801352bd9caf
Create Date: 2026-02-19 22:29:26.472354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7cf35ece55'
down_revision: Union[str, Sequence[str], None] = '801352bd9caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hockey_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('win_pct', sa.Float(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goal_diff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint("team_name", "year", name="uq_team_year")
    )
    op.create_index(op.f('ix_hockey_teams_id'), 'hockey_teams', ['id'], unique=False)
    op.create_table('oscar_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('nominations', sa.Integer(), nullable=True),
    sa.Column('awards', sa.Integer(), nullable=True),
    sa.Column('best_picture', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint("title", "year", name="uq_title_year")
    )
    op.create_index(op.f('ix_oscar_films_id'), 'oscar_films', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oscar_films_id'), table_name='oscar_films')
    op.drop_table('oscar_films')
    op.drop_index(op.f('ix_hockey_teams_id'), table_name='hockey_teams')
    op.drop_table('hockey_teams')
    # ### end Alembic commands ###
